### ISSUE TITLE
Cannot create Segment after loading image and embeddings

### ISSUE THREAD

**Issue by rjkowalski** [fsemerar/SlicerTomoSAM#2] opened 2023-06-26 13:03 UTC
I am trying to get TomoSAM up and running.  I downloaded your sample "spleen_20.tif" and "spleen_20.pkl" from the Box directory and have these files in the same directory.  I open Slicer 5.2.2 on my MacBook Pro (M2 Pro) running macOS 13.4.1 and get the following output in the Python terminal within 3D Slicer when I click on the "Add" button under Segment:

Reading image ... Done
Reading Embeddings ... Done
Traceback (most recent call last):
  File "/Users/my_user/GitHub/SlicerTomoSAM/TomoSAM/tomosam.py", line 251, in updateParameterNodeFromGUI
    self._parameterNode.SetNodeReferenceID("tomosamIncludePoints", self.ui.markupsInclude.currentNode().GetID())
AttributeError: 'NoneType' object has no attribute 'GetID'
Traceback (most recent call last):
  File "/Users/my_user/GitHub/SlicerTomoSAM/TomoSAM/tomosam.py", line 420, in onPushSegmentAdd
    self.clearPoints()
  File "/Users/my_user/GitHub/SlicerTomoSAM/TomoSAM/tomosam.py", line 392, in clearPoints
    self._parameterNode.GetNodeReference("tomosamIncludePoints").RemoveAllControlPoints()
AttributeError: 'NoneType' object has no attribute 'RemoveAllControlPoints'

**Comment by fsemerar** [comment] 2023-06-27 00:50
Hi, did you import the tiff into Slicer by dragging and dropping it? We show an example in [our tutorial](https://youtu.be/4nXCYrvBSjk)

**Comment by rjkowalski** [comment] 2023-06-27 12:58
@fsemerar - yes, I did just that.  Dragged the .tif file into the 3D Slicer UI and the embeddings file is located in the same directory.

**Comment by fsemerar** [comment] 2023-06-27 16:14
<img width="549" alt="image" src="https://github.com/fsemerar/SlicerTomoSAM/assets/85373501/d28c17bf-af1f-4252-9f0a-45a4a88432f4">

I'm trying to understand where this could have gone wrong, can you make sure that the embeddings have actually been imported into Slicer? If not, click on the three dots and select the .pkl file manually

**Comment by rjkowalski** [comment] 2023-06-27 16:41
See attached.  I just tried again and this is what happens as soon as I drag "spleen_20.tif" into the UI.  The embeddings seem to import as expected.
<img width="1920" alt="Screenshot 2023-06-27 at 1 39 50 PM" src="https://github.com/fsemerar/SlicerTomoSAM/assets/6105569/10a2f3e1-1f6d-4e26-b391-cda6930d2420">

**Comment by fsemerar** [comment] 2023-06-27 16:48
Thank you for your screenshot, I'm currently downloading that spleen file again, it may take a few minutes. Have you tried with a different dataset from Box? Maybe try the lung.tif which I know for a fact that it should work. I will also upload checksums to make sure that the problem is not with the download.

**Comment by fsemerar** [comment] 2023-06-27 17:01
<img width="2628" alt="image" src="https://github.com/fsemerar/SlicerTomoSAM/assets/85373501/b2ac4765-2b9d-4ecb-b76e-d09485a924c6">

Actually it works fine for me, so all I can think of is that the pkl file you downloaded got somehow corrupted. Can you check that running "md5 spleen_20.pkl" you get this: MD5 (spleen_20.pkl) = 4abaaecabb496c75ca9a677b372d2200

**Comment by rjkowalski** [comment] 2023-06-27 17:07
It looks to match your output: MD5 (spleen_20.pkl) = 4abaaecabb496c75ca9a677b372d2200

I downloaded lung.tif & lung.pkl and I see the same issue.  This is what I have for lung.pkl:  MD5 (lung.pkl) = 72e1e6f2faee10237a4184ec37ea99c2

**Comment by fsemerar** [comment] 2023-06-27 17:18
hm, I'm a bit confused about what the problem could be to be honest. Let's do this, today I'm going to tackle the changes that were requested by the Slicer developers to make TomoSAM available through their Extension Manager (you can follow the status here https://github.com/Slicer/ExtensionsIndex/pull/1944). Hopefully you should be able to reinstall TomoSAM from there very soon, which might also solve your problem. Stay tuned, I think it should be released by today or tomorrow. Sorry for not being able to fix it right away, I hope that reinstalling the extension from there will solve your problem

**Comment by rjkowalski** [comment] 2023-06-27 17:19
Thanks @fsemerar - I'll keep watch and try that next.

**Comment by fsemerar** [comment] 2023-07-02 19:06
The PR has just been merged and TomoSAM should appear within the Slicer Extension Manager tomorrow

**Comment by fsemerar** [comment] 2023-07-03 21:11
@rjkowalski TomoSAM is now part of the Extension Manager in the Preview Release of Slicer (should appear soon for the stable release as well). Would you mind giving that a try?

**Closed** 2023-07-04 00:21 UTC

**Comment by rjkowalski** [comment] 2023-07-04 13:21
@fsemerar - thanks for the update.  Yes, I just installed it using the stable release (5.2.2).  From the errors you see below, it appears as though the previous installation tomosam.py is being called.  Any suggestions?  
<img width="1919" alt="Screenshot 2023-07-04 at 10 17 50 AM" src="https://github.com/fsemerar/SlicerTomoSAM/assets/6105569/a74b14bb-fd42-491f-ac17-f683be4b1ac2">

**Comment by rjkowalski** [comment] 2023-07-04 13:36
@fsemerar - I removed the old repo entirely and seem to making progress:

<img width="1918" alt="Screenshot 2023-07-04 at 10 34 52 AM" src="https://github.com/fsemerar/SlicerTomoSAM/assets/6105569/499a6211-4994-477b-95e8-6e7b40d4b815">
